# Generated by Django 4.2.1 on 2024-02-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='timeout',
            field=models.IntegerField(default=0),
        ),
    ]
