# Generated by Django 4.2.1 on 2024-02-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_question_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=30000000),
        ),
    ]
